# Generated by Django 5.1 on 2024-08-20 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProfileField",
            new_name="Addnewfield",
        ),
    ]
